export const RULES = {
  IS_REQUIRED: "required",
  REQUIRED: "Required",
  MIN_LENGTH: "minLength",
  MAX_LENGTH: "maxLength",
  MIN: "min",
  MAX: "max",
  IS_DISABLED: "isDisabled",
  ALLOW_FUTURE_DATES: "allowFutureDates",
  MIN_DATE: "minDate",
  MAX_DATE: "maxDate",
  DATE: "Date",
  REGULAR_EXP: "pattern",
};

export const FIELD_TYPES = {
  TEXT: "Text",
  NUMBER: "Number",
  DECIMAL: "Decimal",
  EMAIL: "Email",
  PASSWORD: "Password",
  DATE: "Date",
  CHECKBOX: "Checkbox",
  //RADIO_BUTTON:'RadioButton',
  RADIO_BUTTON: "Bool",
  TEXTAREA: "TextArea",
  RANGE_PICKER: "RangePicker",
  //DROPDOWN:'Dropdown',
  DROPDOWN: "Select",
  MULTISELECT: "MultiSelect",
  READ_ONLY: "ReadOnly",
};

export const DATE_FORMAT = {
  YEAR_MONTH_DAY_WITHOUT_SEPARATOR: "yyMMdd",
  MONTH_SLASH_DAY_SLASH_YEAR: "MM/dd/yyyy",
  MONTH_SLASH_DAY_SLASH_YEAR_MOMENT: "MM/DD/YYYY",
  MONTH_DAY_YEAR: "MM-dd-yyyy",
  YEAR_MONTH_DAY: "yyyy-MM-dd",
  SHORTMONTH_DATE: "MMM dd",
  SHORTMONTH_DATE_YEAR: "MMM dd, yyyy",
  MONTH_SLASH_DAY_SLASH_YEAR_HOUR_MIN: "MM/dd/yyyy HH:mm",
  MONTH_DATE: "MMMM dd",
  MONTH_DATE_YEAR: "MMMM dd, yyyy",
  DAYNAME_SHORTMONTH_DATE_YEAR: "EEEE MMM dd, yyyy",
  ONLY_DAY: "EEEE",
  WEEKNO_SHORTDAY_MONTH_SLASH_DAY_SLASH_YEAR: "I - E - MM/dd/yyyy",
  WEEK_NO: "I",
  MONTH_SLASH_DAY: "MM/dd",
  HOUR_MINUTE_12F: "hh:mm a",
  DD_MMM_YYYY: "DD MMM, YYYY",
  dd_MMM_yyyy: "dd MMM, yyyy",
};
